### ISSUE TITLE
Kaffe kochen

### ISSUE THREAD

**Issue by AttFo-Niklas** [AttFo-Niklas/MEGAfume#4]
Soll Kaffe kochen können!

**Comment by AttFo-Volker** [comment]
Kann er doch schon, oder?

**Comment by AttFo-Volker** [comment]
[Was geht ab.docx](https://github.com/AttFo-Niklas/MEGAfume/files/2965530/Was.geht.ab.docx)

**Comment by AttFo-Niklas** [comment]
Stimmt, damit kann ich das hier schließen!

**Comment by AttFo-Volker** [comment]
Wieso closed?
